USE administrador_IndieIsland;

CREATE TABLE USUARIO(
id_usuario INT IDENTITY(1,1) PRIMARY KEY,
nombre VARCHAR(50),
contrasena NVARCHAR (255),
email NVARCHAR(100) NOT NULL
);

CREATE TABLE FAVORITO(
    id_favorito INT IDENTITY(1,1) PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_juego INT NOT NULL
    CONSTRAINT FK_FAVORITO_USUARIO FOREIGN KEY (id_usuario)
    REFERENCES USUARIO(id_usuario)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);